id: I7DA4A7CB
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:17.420578
last_modified: 2023-01-04 11:29:17.420591
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  EF4C:
    title: A Prayer for the Swift Rebirth of Pewar Rinpoche
    base_file: EF4C.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
